# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SaSMLKitUoNiD_bZWno7D_1-Vtof75Vp
"""

import matplotlib.pyplot as plt

def prime_factors(n):
    i = 2
    factors = []
    while i * i <= n:
        if n % i:
            i += 1
        else:
            n //= i
            factors.append(i)
    if n > 1:
        factors.append(n)
    return factors

def plot_prime_factors(start, end):
    x = []
    y1 = []
    y2 = []
    for i in range(start, end+1):
        factors = prime_factors(i)
        if len(factors) == 2:
            x.append(i)
            y1.append(min(factors)/max(factors))
            y2.append(max(factors)/min(factors))

    plt.plot(x, y1, label='Smaller/Larger')
    plt.plot(x, y2, label='Larger/Smaller')

    plt.xlabel('Number')
    plt.ylabel('Ratio of Prime Factors')
    plt.title('Ratio of Prime Factors for Semiprimes in Given Range')
    plt.legend()
    plt.show()

# Example usage
plot_prime_factors(100, 500)

